/**
 * Creates `.env.local` with admin + DB defaults if the file does not exist yet.
 * Run: npm run seed:admin
 */
import fs from "fs";
import path from "path";
import { generateAdminSessionSecret, DEFAULT_ADMIN_PASSWORD, DEFAULT_ADMIN_USERNAME } from "../src/lib/admin-config";

const root = process.cwd();
const target = path.join(root, ".env.local");

if (fs.existsSync(target)) {
  console.log(".env.local already exists — not overwriting.");
  console.log("To reset admin env only, edit ADMIN_USERNAME / ADMIN_PASSWORD / ADMIN_SESSION_SECRET manually.");
  process.exit(0);
}

const sessionSecret = generateAdminSessionSecret();

const body = `# Generated by npm run seed:admin — rotate secrets before production
DATABASE_URL=file:./data/portfolio.db
ADMIN_USERNAME=${DEFAULT_ADMIN_USERNAME}
ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
ADMIN_SESSION_SECRET=${sessionSecret}
`;

fs.writeFileSync(target, body, "utf8");
console.log("Wrote .env.local with admin ID, password, and a random ADMIN_SESSION_SECRET.");
console.log("Next: npm run db:migrate && npm run db:seed && npm run dev");
